--
-- PostgreSQL database dump
--

\restrict bRncQFNjLO13jncysSH7qwcGI0bMMY5Vf7eiYxYrXao01OLuc6bbylVsGo5vnLK

-- Dumped from database version 17.10 (Homebrew)
-- Dumped by pg_dump version 17.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255),
    action_time timestamp(6) without time zone,
    description character varying(500),
    module character varying(255),
    property_id bigint,
    user_id bigint
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: due_diligence_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.due_diligence_reports (
    id bigint NOT NULL,
    generated_at timestamp(6) without time zone,
    owner_name character varying(255),
    property_id bigint,
    property_title character varying(255),
    recommendation character varying(1000),
    risk_level character varying(255),
    total_risk_score integer
);


ALTER TABLE public.due_diligence_reports OWNER TO postgres;

--
-- Name: due_diligence_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.due_diligence_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.due_diligence_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: environmental; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.environmental (
    id bigint NOT NULL,
    environmental_risk character varying(255),
    pollution_level character varying(255),
    protected_area character varying(255),
    remarks character varying(255),
    property_id bigint
);


ALTER TABLE public.environmental OWNER TO postgres;

--
-- Name: environmental_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.environmental ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.environmental_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flood_zone; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flood_zone (
    id bigint NOT NULL,
    authority character varying(255),
    insurance_required character varying(255),
    risk_level character varying(255),
    zone_type character varying(255),
    property_id bigint
);


ALTER TABLE public.flood_zone OWNER TO postgres;

--
-- Name: flood_zone_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.flood_zone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flood_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: land_registry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.land_registry (
    id bigint NOT NULL,
    last_updated character varying(255),
    registry_number character varying(255),
    registry_office character varying(255),
    registry_status character varying(255),
    title_verified boolean NOT NULL,
    property_id bigint
);


ALTER TABLE public.land_registry OWNER TO postgres;

--
-- Name: land_registry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.land_registry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.land_registry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: legal_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.legal_record (
    id bigint NOT NULL,
    case_status character varying(255),
    court_cases character varying(255),
    remarks character varying(255),
    property_id bigint
);


ALTER TABLE public.legal_record OWNER TO postgres;

--
-- Name: legal_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.legal_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.legal_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mobile_otp_tokens; Type: TABLE; Schema: public; Owner: astitvaraj
--

CREATE TABLE public.mobile_otp_tokens (
    id bigint NOT NULL,
    expiry_time timestamp(6) without time zone NOT NULL,
    mobile_number character varying(255) NOT NULL,
    otp character varying(255) NOT NULL,
    verified boolean NOT NULL
);


ALTER TABLE public.mobile_otp_tokens OWNER TO astitvaraj;

--
-- Name: mobile_otp_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: astitvaraj
--

ALTER TABLE public.mobile_otp_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mobile_otp_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_tokens; Type: TABLE; Schema: public; Owner: astitvaraj
--

CREATE TABLE public.otp_tokens (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    otp character varying(255) NOT NULL,
    verified boolean NOT NULL,
    expiry_time timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.otp_tokens OWNER TO astitvaraj;

--
-- Name: otp_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: astitvaraj
--

ALTER TABLE public.otp_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ownership; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ownership (
    id bigint NOT NULL,
    owner_verified boolean NOT NULL,
    ownership_since character varying(255),
    ownership_type character varying(255),
    remarks character varying(255),
    property_id bigint
);


ALTER TABLE public.ownership OWNER TO postgres;

--
-- Name: ownership_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ownership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ownership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permit (
    id bigint NOT NULL,
    issuing_authority character varying(255),
    permit_number character varying(255),
    permit_status character varying(255),
    permit_type character varying(255),
    property_id bigint
);


ALTER TABLE public.permit OWNER TO postgres;

--
-- Name: permit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties; Type: TABLE; Schema: public; Owner: astitvaraj
--

CREATE TABLE public.properties (
    id bigint NOT NULL,
    address character varying(255),
    area double precision,
    city character varying(255),
    owner_name character varying(255),
    price double precision,
    property_type character varying(255),
    state character varying(255),
    title character varying(255),
    user_id bigint,
    registration_date date,
    verification_date date,
    verification_score double precision,
    verification_status character varying(255),
    latitude double precision,
    longitude double precision,
    ai_report text
);


ALTER TABLE public.properties OWNER TO astitvaraj;

--
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: astitvaraj
--

ALTER TABLE public.properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_tax_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.property_tax_history (
    id bigint NOT NULL,
    payment_date date,
    payment_status character varying(255),
    tax_amount double precision,
    tax_year integer,
    property_id bigint
);


ALTER TABLE public.property_tax_history OWNER TO postgres;

--
-- Name: property_tax_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.property_tax_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_tax_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: risk_assessment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.risk_assessment (
    id bigint NOT NULL,
    crime_risk integer NOT NULL,
    documentation_risk integer NOT NULL,
    environmental_risk integer NOT NULL,
    infrastructure_risk integer NOT NULL,
    legal_risk integer NOT NULL,
    market_risk integer NOT NULL,
    property_id bigint,
    recommendation character varying(500),
    risk_level character varying(255),
    total_score integer NOT NULL
);


ALTER TABLE public.risk_assessment OWNER TO postgres;

--
-- Name: risk_assessment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.risk_assessment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.risk_assessment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: astitvaraj
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    google_id character varying(255),
    mobile_number character varying(255),
    mobile_verified boolean NOT NULL,
    password character varying(255),
    profile_picture character varying(255),
    provider character varying(255) NOT NULL,
    role character varying(255),
    phone character varying(255),
    joined_date date,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER'::character varying, 'AGENT'::character varying, 'LEGAL_REVIEWER'::character varying, 'FINANCIAL_INSTITUTION'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO astitvaraj;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: astitvaraj
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zoning; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zoning (
    id bigint NOT NULL,
    authority character varying(255),
    construction_allowed character varying(255),
    zone_type character varying(255),
    property_id bigint
);


ALTER TABLE public.zoning OWNER TO postgres;

--
-- Name: zoning_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zoning ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zoning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_logs (id, action, action_time, description, module, property_id, user_id) FROM stdin;
1	GENERATE_REPORT	2026-08-11 20:22:46.185677	Generated due diligence report for property ID 19	Due Diligence	19	1
2	GENERATE_REPORT	2026-08-11 20:22:54.296242	Generated due diligence report for property ID 19	Due Diligence	19	1
3	GENERATE_REPORT	2026-08-11 21:44:23.214479	Generated due diligence report for property ID 20	Due Diligence	20	1
4	GENERATE_REPORT	2026-08-11 21:54:05.415811	Generated due diligence report for property ID 20	Due Diligence	20	1
5	GENERATE_REPORT	2026-08-11 21:57:41.468439	Generated due diligence report for property ID 20	Due Diligence	20	1
6	GENERATE_REPORT	2026-08-12 00:20:11.840345	Generated due diligence report for property ID 2	Due Diligence	2	1
7	GENERATE_REPORT	2026-08-12 14:09:50.812256	Generated due diligence report for property ID 2	Due Diligence	2	1
\.


--
-- Data for Name: due_diligence_reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.due_diligence_reports (id, generated_at, owner_name, property_id, property_title, recommendation, risk_level, total_risk_score) FROM stdin;
1	2026-08-11 20:22:46.138267	abc	19	prop 1	\N	\N	\N
2	2026-08-11 20:22:54.291012	abc	19	prop 1	\N	\N	\N
3	2026-08-11 21:44:23.201632	Rahul Sharma	20	Villa	\N	\N	\N
4	2026-08-11 21:54:05.385104	Rahul Sharma	20	Villa	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
5	2026-08-11 21:57:41.46432	Rahul Sharma	20	Villa	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
6	2026-08-12 00:20:11.823549	Rahul Sharma	2	Luxury Villa	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
7	2026-08-12 14:09:50.785884	Rahul Sharma	2	Luxury Villa	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
\.


--
-- Data for Name: environmental; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.environmental (id, environmental_risk, pollution_level, protected_area, remarks, property_id) FROM stdin;
\.


--
-- Data for Name: flood_zone; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.flood_zone (id, authority, insurance_required, risk_level, zone_type, property_id) FROM stdin;
\.


--
-- Data for Name: land_registry; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.land_registry (id, last_updated, registry_number, registry_office, registry_status, title_verified, property_id) FROM stdin;
\.


--
-- Data for Name: legal_record; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.legal_record (id, case_status, court_cases, remarks, property_id) FROM stdin;
\.


--
-- Data for Name: mobile_otp_tokens; Type: TABLE DATA; Schema: public; Owner: astitvaraj
--

COPY public.mobile_otp_tokens (id, expiry_time, mobile_number, otp, verified) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, is_read, message, title, user_id) FROM stdin;
4	2026-08-12 14:09:56.713206	t	Your PDF Due Diligence Report for property ID 2 has been successfully generated and sent to your email.	PDF Report Generated	1
\.


--
-- Data for Name: otp_tokens; Type: TABLE DATA; Schema: public; Owner: astitvaraj
--

COPY public.otp_tokens (id, email, otp, verified, expiry_time) FROM stdin;
1	demo@gmail.com	352397	f	2026-07-21 22:24:32.433826
\.


--
-- Data for Name: ownership; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ownership (id, owner_verified, ownership_since, ownership_type, remarks, property_id) FROM stdin;
\.


--
-- Data for Name: permit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permit (id, issuing_authority, permit_number, permit_status, permit_type, property_id) FROM stdin;
\.


--
-- Data for Name: properties; Type: TABLE DATA; Schema: public; Owner: astitvaraj
--

COPY public.properties (id, address, area, city, owner_name, price, property_type, state, title, user_id, registration_date, verification_date, verification_score, verification_status, latitude, longitude, ai_report) FROM stdin;
2	12 MG Road	3500	Bangalore	Rahul Sharma	12500000	Villa	Karnataka	Luxury Villa	\N	\N	\N	\N	\N	\N	\N	\N
3	street 123	400	Chennai	Demo	1000000	Farmhouse	Tamil Nadu	New property	\N	\N	\N	\N	\N	\N	\N	\N
4	12 Residency Road	121	Mumbai	abc	1299999	house	Maharashtra	new house	\N	\N	\N	\N	\N	\N	\N	\N
5	12 Residency	132	Pune	abcd	2000000	pool	Maharashtra	home	\N	\N	\N	\N	\N	\N	\N	\N
6	agra	122	agra	dsg	121112	house	up	dvsg	9	\N	\N	\N	\N	\N	\N	\N
7	ddfs	321	ses	dsdf	122322	eses	eses	asd	9	\N	\N	\N	\N	\N	\N	\N
9	fgfgc	112	fdfgc	fxfdx	13131	gghfg	gfghch	dfd	9	2026-07-17	\N	0	Pending	\N	\N	\N
11	ffg	122	ggg	fcf	222	gchg	gcgh	sfcg	9	2026-07-17	\N	0	Pending	\N	\N	\N
12	ghgcg	434	gcghc	csf	321112	gvgh	gvgh	sa	9	2026-07-17	\N	0	Pending	\N	\N	\N
13	savdgv	134143	sgahjds	nsvhg	21231	sbdh	shsb	asads	9	2026-07-17	\N	0	Pending	\N	\N	\N
27	54A, A.J.C. Bose Road	200	Kolkata	xyz	3000000	Residential	West Bengal	Villa	5	2026-08-12	2026-08-12	25	REJECTED	22.5726459	88.3638953	# Real Estate Due Diligence Report\\n\\n## Property Overview\\n- **Property ID:** Survey No: 334 / 3A2D (Patta Survey No: 334 / 14, Patta No: 4245)\\n- **Owner Name:** SMT. K. NAGALAKSHMI W/O Mr. KARTHIKEYAN\\n- **Address:** Usilampatti Road, Kombaipatti Village Panchayat, Nilakottai Taluk, Dindigul District\\n- **Property Type:** Proposed Construction of Ground Floor Farm House\\n- **Total Site Area:** 1026.68 Sq.mt (as per site/document)\\n- **Proposed Farm House Area:** 58.18 Sq.mt\\n\\n## Technical Details\\n- **Structure:** R.C.C. Roof building.\\n- **Components:** Includes Site Plan, Elevation, Section View, Septic Tank Details, Rain Water Harvesting (RWH) Tank Details, and Staircase Details.\\n- **Boundaries:** North: Dry Land, South: Main Road, East: Dry Land, West: Way to Batlagundu/Usilampatti.\\n\\n## Compliance & Signatures\\n- **Applicant Signature:** Present (K. Nagalakshmi).\\n- **Structural Engineer:** Signed and Sealed (Dr. V.P. Chellapandian, Vetrivel Construction, Reg No: SE 08 / 2019 (GR-I)).\\n- **Authority Approval:** Digital signature stamp present on the bottom left, however, it is explicitly flagged as **\\"Signature Not Verified\\"** with a timestamp of 2024.03.13.\\n- **Office Use Block:** Currently blank/empty.\\n\\n## Identified Risks & Anomalies\\n1. **Unverified Digital Signature:** The digital signature for the plan approval is marked as \\"Not Verified,\\" which may indicate a technical failure in the document's validation or a placeholder that has not been finalized by the local panchayat/planning authority.\\n2. **Missing Official Sanction:** The \\"Office Use\\" section is completely empty. There is no official seal or reference number from the Nilakottai Taluk or Dindigul District planning department.\\n3. **Access Easement:** The site plan indicates a \\"7.10 CART PATH\\" adjacent to the property. Due diligence should confirm whether this is a public right-of-way or a private easement that could affect property boundaries.\\n\\n## Conclusion\\nThe document provides comprehensive technical details for the proposed farm house. However, because the official approval signature is unverified and the office use block is empty, the legal status of the building permit is currently inconclusive.
1	12 MG Road	3200	Bangalore	Rahul Sharma	12500000	Villa	Karnataka	Luxury Villa	\N	\N	2026-08-12	100	Verified	\N	\N	\N
24	Pune City HO	100	Pune	Rahul Sharma	2000000	Land	Maharashtra	Farm house	1	2026-08-11	\N	0	Pending	18.5213738	73.8545071	\N
23	Ward no.11	100	Forbesganj	Astitva Raj	1000000	Residential	Bihar	Villa	1	2026-08-11	2026-08-12	100	Verified	26.3049106	87.2632847	\N
10	xfgf	123	fdf	ffd	23222	dtrd	dr	vghg	\N	2026-07-17	2026-08-12	0	Rejected	\N	\N	\N
8	dsd	213	dss	dfs	223433	dsd	dsds	szdd	\N	2026-07-17	2026-08-12	0	Rejected	\N	\N	\N
25	Amber	50	Jaipur	ab	1000000	Agricultural	Rajasthan	Farm	1	2026-08-12	2026-08-12	100	Verified	26.9888269	75.8558916	\N
26	Mysore	100	Kumbalgodu	ABC	2000000	Residential	Karnataka	Farm House	5	2026-08-12	\N	0	REJECTED	\N	\N	# Real Estate Due Diligence Report\\n\\n## Property Identification\\n- **Property ID (Patta No):** 4245\\n- **Survey Numbers:** 334 / 3A2D (Document Survey No) and 334 / 14 (Patta Survey No)\\n- **Owner Name:** Smt. K. Nagalakshmi (W/O Mr. Karthikeyan)\\n- **Address:** Usilampatti Road, Kombaipatti Village Panchayat, Nilakottai Taluk, Dindigul District\\n\\n## Technical Specifications\\n- **Total Site Area:** 1026.68 Sqmt (as per Site/Document)\\n- **FMB/PLR Site Area:** 1026.00 Sqmt\\n- **Farm House Built-up Area:** 58.18 Sqmt\\n- **Structure Type:** R.C.C. Roof Ground Floor Farm House\\n\\n## Due Diligence Findings\\n### 1. Legal & Regulatory Anomalies\\n- **Area Discrepancy:** There is a minor discrepancy of 0.68 Sqmt between the FMB/PLR records (1026.00 Sqmt) and the Document/Site measurement (1026.68 Sqmt).\\n- **Survey Number Variation:** The document references both Survey No 334/3A2D and 334/14. Verification is required to ensure the subdivision (3A2D) is correctly mapped to the parent Patta survey.\\n\\n### 2. Signature & Verification Status\\n- **Digital Signature Risk:** A digital stamp on the bottom-left corner explicitly states **"Signature Not Verified"**, dated 2024.03.13. This indicates that the electronic certificate on the plan has not been authenticated by the issuing authority's server.\\n- **Professional Signatures:** Physical-style signatures for the Applicant (K. Nagalakshmi) and the Structural Engineer (Dr. V.P. Chellapandian, Reg. No. SE 08/2019) are present.\\n\\n### 3. Risks & Recommendations\\n- **High Risk:** The unverified digital signature may invalidate the plan for official building permit purposes. The document must be re-validated through the official government portal.\\n- **Boundary Check:** The site plan shows a "7.10 CART PATH" on the eastern boundary; legal access rights to this path should be verified in the parent deed.\\n\\n## Final Status\\n**Status: PENDING VALIDATION**
\.


--
-- Data for Name: property_tax_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.property_tax_history (id, payment_date, payment_status, tax_amount, tax_year, property_id) FROM stdin;
\.


--
-- Data for Name: risk_assessment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.risk_assessment (id, crime_risk, documentation_risk, environmental_risk, infrastructure_risk, legal_risk, market_risk, property_id, recommendation, risk_level, total_score) FROM stdin;
1	0	40	0	5	0	0	19	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
2	0	40	0	5	0	0	20	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
3	0	40	0	5	0	0	24	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
4	0	30	0	0	0	5	2	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
5	0	30	0	5	0	0	3	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
6	0	40	0	5	0	0	8	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
7	0	10	0	5	0	0	25	Obtain construction permit.	LOW	15
8	0	10	0	5	0	0	23	Obtain construction permit.	LOW	15
9	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
10	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
11	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
12	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
13	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
14	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
15	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
16	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
17	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
18	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
19	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
20	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
21	0	40	0	5	0	0	26	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
23	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
25	0	40	0	5	0	0	10	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
22	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
24	0	30	0	5	0	0	5	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
26	0	40	0	5	0	0	12	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
27	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
28	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
30	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
29	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
31	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
32	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
33	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
34	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
35	0	30	0	5	0	0	6	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
36	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
37	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
38	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
39	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
40	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
41	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
42	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
43	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
44	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
45	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
46	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
47	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
48	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
49	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
50	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
51	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
52	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
53	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
54	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
55	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
56	0	10	0	5	0	0	27	Obtain construction permit.	LOW	15
57	0	40	0	5	0	0	27	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
58	0	40	0	5	0	0	27	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
60	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
59	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
61	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
62	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
63	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
64	0	40	0	5	0	0	27	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
65	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
66	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
67	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
68	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
69	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
70	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
71	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
72	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
73	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
74	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
75	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
76	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
77	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
78	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
79	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
80	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
81	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
84	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
82	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
83	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
85	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
86	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
87	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
88	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
89	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
90	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
91	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
93	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
92	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
94	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
95	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
96	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
97	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
98	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
99	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
100	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
101	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
102	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
103	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
104	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
105	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
106	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
107	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
108	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
109	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
110	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
111	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
113	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
120	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
114	0	30	0	5	0	0	7	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
118	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
112	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
115	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
121	0	30	0	5	0	0	4	Property verification is incomplete. Obtain construction permit.	MEDIUM	35
116	0	40	0	5	0	0	9	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
119	0	40	0	5	0	0	11	Property verification is incomplete. Obtain construction permit.	MEDIUM	45
117	0	40	0	0	0	0	13	Property verification is incomplete. Obtain construction permit.	MEDIUM	40
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: astitvaraj
--

COPY public.users (id, email, full_name, google_id, mobile_number, mobile_verified, password, profile_picture, provider, role, phone, joined_date, is_active) FROM stdin;
1	astitvarajfbg@gmail.com	Astitva Raj	117202130235077247239	8789709535	t	$2a$10$WDdX1.2rtgA0nMBTqXCLpuNAA4Qxy5AO9oRWyFwOAIB9Mek6KlIcq	https://lh3.googleusercontent.com/a/ACg8ocLJ70ZilChUoYL6PWepTBpuDLlyJ1wj4MMVQIn8cUKWugr9AnE=s96-c	GOOGLE	ADMIN	8789709535	\N	t
5	abhi202456@gmail.com	Abhi	\N	\N	f	$2a$10$wap8jxt.LMS3K6H74ywet.AHbwh6iDuKMPRn/Ef0BS/TGu.Atk/cS	\N	LOCAL	BUYER	\N	\N	t
\.


--
-- Data for Name: zoning; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zoning (id, authority, construction_allowed, zone_type, property_id) FROM stdin;
\.


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 7, true);


--
-- Name: due_diligence_reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.due_diligence_reports_id_seq', 7, true);


--
-- Name: environmental_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.environmental_id_seq', 1, false);


--
-- Name: flood_zone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.flood_zone_id_seq', 1, false);


--
-- Name: land_registry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.land_registry_id_seq', 1, false);


--
-- Name: legal_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.legal_record_id_seq', 1, false);


--
-- Name: mobile_otp_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: astitvaraj
--

SELECT pg_catalog.setval('public.mobile_otp_tokens_id_seq', 9, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 4, true);


--
-- Name: otp_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: astitvaraj
--

SELECT pg_catalog.setval('public.otp_tokens_id_seq', 7, true);


--
-- Name: ownership_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ownership_id_seq', 1, false);


--
-- Name: permit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permit_id_seq', 1, false);


--
-- Name: properties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: astitvaraj
--

SELECT pg_catalog.setval('public.properties_id_seq', 27, true);


--
-- Name: property_tax_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.property_tax_history_id_seq', 1, false);


--
-- Name: risk_assessment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.risk_assessment_id_seq', 121, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: astitvaraj
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: zoning_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zoning_id_seq', 1, false);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: due_diligence_reports due_diligence_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.due_diligence_reports
    ADD CONSTRAINT due_diligence_reports_pkey PRIMARY KEY (id);


--
-- Name: environmental environmental_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environmental
    ADD CONSTRAINT environmental_pkey PRIMARY KEY (id);


--
-- Name: flood_zone flood_zone_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flood_zone
    ADD CONSTRAINT flood_zone_pkey PRIMARY KEY (id);


--
-- Name: land_registry land_registry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.land_registry
    ADD CONSTRAINT land_registry_pkey PRIMARY KEY (id);


--
-- Name: legal_record legal_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.legal_record
    ADD CONSTRAINT legal_record_pkey PRIMARY KEY (id);


--
-- Name: mobile_otp_tokens mobile_otp_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.mobile_otp_tokens
    ADD CONSTRAINT mobile_otp_tokens_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: otp_tokens otp_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT otp_tokens_pkey PRIMARY KEY (id);


--
-- Name: ownership ownership_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT ownership_pkey PRIMARY KEY (id);


--
-- Name: permit permit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permit
    ADD CONSTRAINT permit_pkey PRIMARY KEY (id);


--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- Name: property_tax_history property_tax_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.property_tax_history
    ADD CONSTRAINT property_tax_history_pkey PRIMARY KEY (id);


--
-- Name: risk_assessment risk_assessment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.risk_assessment
    ADD CONSTRAINT risk_assessment_pkey PRIMARY KEY (id);


--
-- Name: zoning uk3a5viy8pn9nenr46vt3og9v4j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoning
    ADD CONSTRAINT uk3a5viy8pn9nenr46vt3og9v4j UNIQUE (property_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: flood_zone ukah2dj3wcuuvo0pjy59v7hlmt8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flood_zone
    ADD CONSTRAINT ukah2dj3wcuuvo0pjy59v7hlmt8 UNIQUE (property_id);


--
-- Name: mobile_otp_tokens ukb33dgfgnd7p0qnqavdwlp2eh0; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.mobile_otp_tokens
    ADD CONSTRAINT ukb33dgfgnd7p0qnqavdwlp2eh0 UNIQUE (mobile_number);


--
-- Name: legal_record ukeoxj4wda5rl0muia43hyf3yau; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.legal_record
    ADD CONSTRAINT ukeoxj4wda5rl0muia43hyf3yau UNIQUE (property_id);


--
-- Name: permit ukjqa9q20t5dof5kuac4y8ocv03; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permit
    ADD CONSTRAINT ukjqa9q20t5dof5kuac4y8ocv03 UNIQUE (property_id);


--
-- Name: environmental ukkyf8o1onlq2rt0suq8ntk0mec; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environmental
    ADD CONSTRAINT ukkyf8o1onlq2rt0suq8ntk0mec UNIQUE (property_id);


--
-- Name: land_registry uklfjh9kfyymehtx4r0ytg2pqr0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.land_registry
    ADD CONSTRAINT uklfjh9kfyymehtx4r0ytg2pqr0 UNIQUE (property_id);


--
-- Name: ownership ukmhwkye5b7f73p3kj99uus722b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT ukmhwkye5b7f73p3kj99uus722b UNIQUE (property_id);


--
-- Name: users ukovh8xmu9ac27t18m56gri58i1; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukovh8xmu9ac27t18m56gri58i1 UNIQUE (google_id);


--
-- Name: users ukr7c96a004bv8w16jgdm8imich; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr7c96a004bv8w16jgdm8imich UNIQUE (mobile_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: astitvaraj
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: zoning zoning_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoning
    ADD CONSTRAINT zoning_pkey PRIMARY KEY (id);


--
-- Name: land_registry fk14u97bey9c7luwgm3dhns73ey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.land_registry
    ADD CONSTRAINT fk14u97bey9c7luwgm3dhns73ey FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: ownership fk4005d4rf92bdrb39dt3t1uqy5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ownership
    ADD CONSTRAINT fk4005d4rf92bdrb39dt3t1uqy5 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: zoning fkc1hcfeu281wim1lf18l8tj0m1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoning
    ADD CONSTRAINT fkc1hcfeu281wim1lf18l8tj0m1 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: permit fkd1d1sdpq094enketho4k2e6gy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permit
    ADD CONSTRAINT fkd1d1sdpq094enketho4k2e6gy FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: flood_zone fkhf2tggbgjkknq9s410ak7wudq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flood_zone
    ADD CONSTRAINT fkhf2tggbgjkknq9s410ak7wudq FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: environmental fkj1n4wfal2oh3ym09mxxlc3cc3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environmental
    ADD CONSTRAINT fkj1n4wfal2oh3ym09mxxlc3cc3 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: property_tax_history fknbauka7lo3t9mulbquybv6ba7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.property_tax_history
    ADD CONSTRAINT fknbauka7lo3t9mulbquybv6ba7 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: legal_record fks9g11ay52w4m794a866w7r2e9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.legal_record
    ADD CONSTRAINT fks9g11ay52w4m794a866w7r2e9 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bRncQFNjLO13jncysSH7qwcGI0bMMY5Vf7eiYxYrXao01OLuc6bbylVsGo5vnLK

