spring.application.name=due-diligence-agent
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/real_estate_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# ==========================
# JPA Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# File Upload Configuration
# ==========================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ==========================
# Server Configuration
# ==========================
server.port=8080

# ==========================
# JWT Configuration
# ==========================
# JWT Secret
jwt.secret=${JWT_SECRET:}

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY:}

jwt.expiration=3600000

# ==========================
# Logging
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# ==========================
# Gmail SMTP Configuration
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=astitvarajfbg@gmail.com
spring.mail.password=luen xlll lifx wmlb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

google.client.id=${GOOGLE_CLIENT_ID:}